### ISSUE TITLE
Missing Event Emitters/Listeners

### ISSUE THREAD

**Issue by derN3rd** [mmkal/handy-redis#10]
Hey

I just wanted to ask if its possible to add event emitters so I can use them to track errors.
I'm using generic-pool to keep multiple redis connections open and I need to listen to error events to remove broken clients from the pool.

With the official redis module I can use `client.on("error", cb)` but there is no current solution on handy-redis.

Thanks in advance

**Comment by mmkal** [comment]
For this I'd recommend just using the underlying redis client which is exposed as `client.redis`.

**Comment by mmkal** [comment]
Closing - to clarify, you can just do this:

```typescript
import { createHandyClient } from 'handy-redis';

const myClient = createHandyClient();
myClient.redis.on("error", cb);
```
