### ISSUE TITLE
RangeError: Maximum call stack size exceeded with large args set

### ISSUE THREAD

**Issue by bamanuel** [mmkal/handy-redis#108]
When calling `handyclient.hmset()` with 200000 args, `flattenDeep()` causes stackoverflow. Is it possible to use `_.flatten()` instead? 

```
(node:9360) UnhandledPromiseRejectionWarning: RangeError: Maximum call stack size exceeded
    at exports.flattenDeep (\node_modules\handy-redis\dist\flatten.js:7:15)
    at Array.map (<anonymous>)
    at Object.exports.flattenDeep (\node_modules\handy-redis\dist\flatten.js:7:30)
    at \node_modules\handy-redis\dist\index.js:18:45
    at new Promise (<anonymous>)
    at Object.handyClient.<computed> [as hmset] (\node_modules\handy-redis\dist\index.js:17:45)
```

Please see https://repl.it/repls/IntrepidCyanScript

Thanks

**Comment by bamanuel** [comment]
The issue still exists when the array is nested. For example:

```
const huge = [range(0, 500000)];
expect(flattenDeep(huge)).toEqual(huge);
```

**Comment by bamanuel** [comment]
I noticed, after fixing `flattenDeep` by replacing the spread operator with for loop, the issue occurs again in index.ts at call to `func.apply()`.

**Comment by mmkal** [comment]
https://github.com/mmkal/handy-redis/pull/182#issuecomment-618333645
