### ISSUE TITLE
Documentation on the options work?

### ISSUE THREAD

**Issue by sjmcdowall** [mmkal/handy-redis#12]
This maybe obvious to others, but as a new user of this -- I find it hard to see what options I can pass, etc. in to get Redis configured correctly.  Maybe a section in the documentation and a sample or two?  Otherwise I am loving the cleanliness of the package!

**Comment by mmkal** [comment]
I'll make this more explicit soon (and keep this open until I do), but for now - the `createHandyClient` function takes a config object exactly the same as what's passed to the node_redis `createClient` function. So the best thing would be to look at the documentation there. You can also pass a node_redis client in.

**Comment by mmkal** [comment]
added a link to the [relevant portion of the docs for node_redis](https://github.com/mmkal/handy-redis#usage) in the readme.
