### ISSUE TITLE
Support redis-mock

### ISSUE THREAD

**Issue by darrenfurr** [mmkal/handy-redis#196]
I'm passing the redis client to handyRedis, but it appears to still attempt to connect on 127.0.0.1:6379.

```
const redis = require("redis-mock");
const handyRedis = require("handy-redis");
const client = handyRedis.createHandyClient(redis.createClient());
```

Results:
```
 console.error
    Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379
        at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1137:16)
```

**Comment by mmkal** [comment]
It looks like redis-mock [doesn't implement `zscan`](https://github.com/yeahoffline/redis-mock/blob/b1ad5a3ffbce523d96b1f53f365f9c575d975bd5/lib/redis-mock.js#L726-L731), which is [what handy-redis checks for](https://github.com/mmkal/handy-redis/blob/66ede5dccc6697ec8eec03bb9ae15723f847adaa/src/index.ts#L16). I can change this to something else to make this work and release an update soon, but in the meantime, you can workaround by setting it to a dummy function:

```js
 const redis = require("redis-mock");
const handyRedis = require("handy-redis");

const mockRedis = redis.createClient();
mockRedis.zscan = () => {};
const client = handyRedis.createHandyClient(mockRedis);
```

Or ask the maintainer of redis-mock to implement it!
