### ISSUE TITLE
How to use SCRIPT LOAD?

### ISSUE THREAD

**Issue by karli2000** [mmkal/handy-redis#221]
Hi,

i love handy-redis, makes it so much easier with Typescript!

But i have one issue: we need Lua-scripts and i am missing the SCRIPT LOAD (https://redis.io/commands/script-load ) command.
I know, i can use it with .redis.script('LOAD') but only with callbacks, or?

Thank you,
Max

**Comment by mmkal** [comment]
Hi @karli2000 - right now it's not supported. https://github.com/redis/redis-doc puts `SCRIPT` and some other commands in a strange format which trips up the codegen. I'm testing out a workaround.

In the meantime, yes I'd use `.redis.script`. There won't be typescript support or documentation, but you can use `import { promisify } from 'util'` to avoid callbacks.

**Comment by mmkal** [comment]
Fixed in [v2](https://github.com/mmkal/handy-redis/releases/tag/v2.0.0)
