### ISSUE TITLE
Overloaded multi commands have incorrect type

### ISSUE THREAD

**Issue by scola84** [mmkal/handy-redis#270]
When I try to use `xadd` on a `batch` I am forced to provide the `NOMKSTREAM` option, while there are four `xadd` definitions available. It seems as if in [multi.ts#L52](https://github.com/mmkal/handy-redis/blob/864eae97a6b217c2ad7fe3bf138315e0634bfceb/src/node_redis/multi.ts#L52) only the last one is added to the batch/multi interface.

**Comment by mmkal** [comment]
Ah, I think this is a limitation of the `Parameters<...>` built-in type (see https://github.com/microsoft/TypeScript/issues/32164). I'll look into whether the whole `multi`/`batch` interface can be generated like the regular commands.

**Comment by mmkal** [comment]
@scola84 fix released in [v2.2.0](https://github.com/mmkal/handy-redis/releases/v2.2.0)

**Comment by scola84** [comment]
Successfully integrated, thanks!
