### ISSUE TITLE
Multi commands pass an array to the underlying redis function

### ISSUE THREAD

**Issue by cfredhart** [mmkal/handy-redis#277]
When setting up the commands for the `WrappedNodeRedisClientImpl.prototype`, the flattened array of parameters are passed using the spread operator in [src/node_redis/index.ts#58](https://github.com/mmkal/handy-redis/blob/9d8965b436df9eedcadb0684ec6a94af0b01fcd1/src/node_redis/index.ts#L58), 
```
return this.nodeRedis[method](...flattenedArgs);
```
however, the flattened array of parameters is passed without using the spread operator in [src/node_redis/multi.ts#L61](https://github.com/mmkal/handy-redis/blob/9d8965b436df9eedcadb0684ec6a94af0b01fcd1/src/node_redis/multi.ts#L61)
```
(this as any).nodeRedisMulti[method](flattenDeep(args));
```

The result appears to be that for multi commands, the wrapped `nodeRedis` instance receives its parameters as a single array whereas non-multi functions receive their arguments as separate arguments. This seems to cause an issue when mocking the underlying redis instance with redis-mock since it does not correctly handle the parameters received from the multi functions.

**Comment by mmkal** [comment]
@cfredhart thanks for the report. I don't see why `...` shouldn't be used for multis too, this is only working now because the underlying client flattens args at runtime too (though I'd argue redis-mock should mirror that behaviour) - would you like to open a PR?

**Comment by cfredhart** [comment]
I can open a PR. I also have a PR open for redis-mock to flatten the args on that side.
