### ISSUE TITLE
TypeError: net.isIP is not a function

### ISSUE THREAD

**Issue by vnguyen972** [mmkal/handy-redis#278]
I'm trying this in my react typescript project.

`npm install handy-redis redis`

then

`import { createNodeRedisClient } from 'handy-redis';
const client = createNodeRedisClient();`

And it gives me error: 
TypeError: net.isIP is not a function.

What am I missing?

REDIS version: 6.0.10
Handy-redis version: ^2.2.1

**Comment by mmkal** [comment]
Hi @vnguyen972 - are you trying to use it the browser (react)? If so, it's not designed for that, this is a nodejs library. I'd suggest looking into something like [nextjs](
