### ISSUE TITLE
TypeError: _.flattenDeep is not a function

### ISSUE THREAD

**Issue by foxundermoon** [mmkal/handy-redis#3]
generated client.js  
line 1282 
 it cause TypeError: _.flattenDeep is not a function

may be type too quick.

handy-redis@1.1.0

```js

     * since: 1.0.0
     *
     * group: generic
     */
    keys(...args) {
        const flattenedArgs = _.flattenDeep(args);
                                                ^^^^^^^^^^^^
        return new Promise((resolve, reject) => {
            this.redis.keys.apply(this.redis, [
                ...flattenedArgs,
                (err, data) => err ? reject(err) : resolve(data),
            ]);
        });
    }

```

**Comment by mmkal** [comment]
Thanks for this @foxundermoon - it was a bug where I assumed a lodash dependency but it wasn't in the prod dependencies section. It should be fixed by https://github.com/mmkal/handy-redis/pull/4 - try updating to version 1.1.1 and let me know if you still have problems.
