### ISSUE TITLE
Add {engines: {node: '>8'}} to package.json

### ISSUE THREAD

**Issue by golopot** [mmkal/handy-redis#38]

**Comment by mmkal** [comment]
@golopot see linked PR. I'm curious what the use case is, since I used the syntax I found in npm's docs, and used `>=` instead of `>` (`>= 8.0.0` rather than `> 8`). Let me know if that doesn't solve the problem you're having for some reason.

**Comment by golopot** [comment]
1. For documentation: users can find the supported node versions in a standard place.
2. Cli validation:  `yarn` will error out if the node version is incompatible with a installed module.
