### ISSUE TITLE
Set command can return null

### ISSUE THREAD

**Issue by JakeCB** [mmkal/handy-redis#42]
Using set with NX or XX can make the command return null. Right now the type definitions for all the set overloads are Promise\<string>. I would guess the fix would be to change the overloads with the "condition" parameter to Promise<string | null>.

The easiest way to test is to make a random set call with XX. You'll get back null from the library.

https://redis.io/commands/set
```Simple string reply: OK if SET was executed correctly. Null reply: a Null Bulk Reply is returned if the SET operation was not performed because the user specified the NX or XX option but the condition was not met.```

**Comment by mmkal** [comment]
Hi @JakeCB, thanks for reporting. I’m able to reproduce this - I’ll add a usage of NX or XX to make sure the types reflect the return value.
