### ISSUE TITLE
Add support for multi

### ISSUE THREAD

**Issue by aequasi** [mmkal/handy-redis#6]
`multi()` shouldn't be promisified, and the type shouldn't be `any`

**Comment by mmkal** [comment]
Fixed with https://github.com/mmkal/handy-redis/pull/7 , thanks for pointing this out. `multi` now uses the underlying client's `multi` function so `exec` isn't promisified. There's a workaround for this documented here: https://github.com/mmkal/handy-redis/blob/master/README.md#multi
