### ISSUE TITLE
@types/redis 2.8.6 is incompatible

### ISSUE THREAD

**Issue by Can-Sahin** [mmkal/handy-redis#9]
Using `@types/redis 2.8.6`

I can't create client with neither `opts` nor `RedisClient`

``` typescript
const opts: Redis.ClientOpts = {
    host: process.env.REDISHOST,
    port: parseInt(process.env.REDISPORT, 10),
    password: process.env.REDISPASSWORD
};
this.testRedisClient = Redis.createClient(opts);
this.handyRedisClient = createHandyClient(opts); // infers opts as RedisClient type. Not working
this.handyRedisClient = createHandyClient(this.testRedisClient); // Error:   Property 'substr' is missing in type 'RedisClient'.
this.handyRedisClient = createHandyClient(1234,'host',opts); // Error:  Types of property 'db' are incompatible. Type 'string | number' is not assignable to type 'string'. Type 'number' is not assignable to type 'string'.
```
None of these initialisation works. Its all fine with `0.12.36` version of `@types/redis`

**Comment by mmkal** [comment]
This is most likely happening because the library pulls in a specific version of @types/redis. So you shouldn't need to add that package explicitly. Everything should work if you remove it. 

That said, I am planning on looking into decoupling from @types/redis or making it a peerDependency.

**Comment by mmkal** [comment]
This is fixed by https://github.com/mmkal/handy-redis/pull/21
